#%RAML 1.0 Trait

headers:
  x-correlation-id:
    type: string
    required: false
    description: Correlation ID passed from the calling process API. If not provided, MuleSoft generates one.
    example: "9d72f3aa-7e10-4d5d-bcb4-1b32fa8d1012"